// drive-executor-codex-template.test.ts — c6: `--executor=codex-cli` drives a
// REAL step through DEFAULT_CODEX_EXECUTOR_TEMPLATE end to end (DoD #1/#3).
//
// ── WHY A REAL SUBPROCESS, NOT AN INJECTED DriveDeps.executor ──────────────
//
// Injecting `deps.executor` (as tests/drive-executor-flag.test.ts does for
// SELECTION coverage) bypasses subprocessExecutor and buildExecutorArgv
// entirely — it would prove `--executor=codex-cli` was accepted, never that
// the TEMPLATE this task built is correct. `tests/executor-conformance.test.ts`
// established the sanctioned pattern for this exact problem: derive an armed
// stand-in from the REAL default template (only the leading binary token
// swapped for a `bun <fake>` script) and set it via `PIPELINE_DRIVE_EXECUTOR_CMD`
// so `--executor=codex-cli` still resolves to DEFAULT_CODEX_EXECUTOR_TEMPLATE's
// own token layout, and the REAL subprocessExecutor/buildExecutorArgv build
// and spawn it. This file follows that pattern for the codex template.
//
// The fake `codex` script plays the ONE channel this task's own investigation
// found reliable for codex-cli — the record FILE the spawn prompt names
// (verified live against the real CLI; see codex-stream.ts's header) — and
// ALSO emits a real codex-shaped `--json` stream, so the argv assertions below
// are checking the REAL template's flags, not a hand-rolled stand-in for them.

import { describe, expect, test, afterEach } from 'bun:test';
import { mkdtempSync, mkdirSync, writeFileSync, readFileSync, rmSync, existsSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import { computePlan } from '../src/lib/plan';
import { DEFAULT_CODEX_EXECUTOR_TEMPLATE, runDrive } from '../src/commands/drive';

const created: string[] = [];
afterEach(() => {
  while (created.length) rmSync(created.pop()!, { recursive: true, force: true });
}, 30000);

// ---------------------------------------------------------------------------
// Scaffold: one v1 step, single-step pipeline (PIPELINE_COMPLETE on step 1)
// ---------------------------------------------------------------------------

function scaffold(): { root: string; stepPath: string } {
  const root = mkdtempSync(join(tmpdir(), 'drive-codex-tmpl-'));
  created.push(root);
  expect(root).not.toContain(' '); // whitespace-split templates cannot carry a space
  writeFileSync(join(root, 'PIPELINE.md'), '# Codex template probe\n\n## End State\ndone\n');
  mkdirSync(join(root, 'steps'), { recursive: true });
  const stepPath = join(root, 'steps', '01-only.md');
  writeFileSync(stepPath, '# only step\n');
  return { root, stepPath };
}

// ---------------------------------------------------------------------------
// The fake `codex` binary — plays the record-file channel + a real --json
// stream, and logs every argv/prompt it was invoked with.
// ---------------------------------------------------------------------------

const FAKE_CODEX_SRC = `// generated by tests/drive-executor-codex-template.test.ts
import { appendFileSync, writeFileSync, mkdirSync } from 'node:fs';
import { dirname } from 'node:path';

const argv = process.argv.slice(2);
const prompt = await Bun.stdin.text();

appendFileSync(process.env.PIPELINE_CODEX_LOG, JSON.stringify({ argv, prompt }) + '\\n', 'utf8');

const m = /^step_record_file = (.+)$/m.exec(prompt);
const recordFile = m ? m[1].trim() : null;
if (recordFile) {
  mkdirSync(dirname(recordFile), { recursive: true });
  writeFileSync(
    recordFile,
    JSON.stringify({
      outcome: 'completed',
      summary: 'codex template probe',
      next_iteration: 'PIPELINE_COMPLETE',
      has_improvement_brief: false,
    }),
    'utf8',
  );
}

process.stdout.write(JSON.stringify({ type: 'thread.started', thread_id: '00000000-0000-0000-0000-000000000000' }) + '\\n');
process.stdout.write(JSON.stringify({ type: 'turn.started' }) + '\\n');
process.stdout.write(JSON.stringify({ type: 'item.completed', item: { id: 'item_0', type: 'agent_message', text: 'DONE' } }) + '\\n');
process.stdout.write(JSON.stringify({ type: 'turn.completed', usage: { input_tokens: 1, output_tokens: 1, cached_input_tokens: 0, cache_write_input_tokens: 0 } }) + '\\n');
process.exit(0);
`;

/** Derive the armed template from the REAL default — only the leading
 *  `codex` binary token is swapped, exactly `executor-conformance.test.ts`'s
 *  own `swap`. Every flag after it is DEFAULT_CODEX_EXECUTOR_TEMPLATE's own. */
function armedTemplate(root: string, fakeCodex: string): string {
  return DEFAULT_CODEX_EXECUTOR_TEMPLATE.replace(/^codex\b/, `bun ${fakeCodex}`);
}

function flagValue(argv: readonly string[], flag: string): string | null {
  const i = argv.indexOf(flag);
  return i >= 0 && i + 1 < argv.length ? argv[i + 1] : null;
}

// ---------------------------------------------------------------------------
// Running one drive invocation, in-process
// ---------------------------------------------------------------------------

const ENV_KEYS = [
  'PIPELINE_DRIVE_EXECUTOR_CMD',
  'PIPELINE_CODEX_LOG',
  'PIPELINE_RUN_ID',
  'PIPELINE_PARENT_RUN_ID',
  'PIPELINE_SYNC_LOCAL_STATS',
  'PIPELINE_STATS_RUNNER',
  'CLAUDE_SESSION_ID',
  'CLAUDE_PLUGIN_ROOT',
  'HOME',
  'USERPROFILE',
] as const;

interface Dispatch {
  argv: string[];
  prompt: string;
}

interface RunResult {
  code: number;
  json: Record<string, unknown> | null;
  stderr: string;
  dispatches: Dispatch[];
}

async function drive(root: string, runId: string, extraArgs: string[], logFile: string): Promise<RunResult> {
  const saved = new Map<string, string | undefined>(ENV_KEYS.map((k) => [k, process.env[k]]));
  const prevCwd = process.cwd();
  let outBuf = '';
  let errBuf = '';
  try {
    process.env.HOME = root;
    process.env.USERPROFILE = root;
    process.env.PIPELINE_CODEX_LOG = logFile;
    for (const k of ['PIPELINE_RUN_ID', 'PIPELINE_PARENT_RUN_ID', 'PIPELINE_SYNC_LOCAL_STATS', 'PIPELINE_STATS_RUNNER', 'CLAUDE_SESSION_ID', 'CLAUDE_PLUGIN_ROOT']) {
      delete process.env[k];
    }
    process.chdir(root);
    const code = await runDrive(['--root', root, '--run-id', runId, ...extraArgs], {
      out: (s) => (outBuf += s),
      err: (s) => (errBuf += s),
    });
    let json: Record<string, unknown> | null = null;
    try {
      json = JSON.parse(outBuf) as Record<string, unknown>;
    } catch {
      /* error paths print nothing on stdout */
    }
    const dispatches: Dispatch[] = existsSync(logFile)
      ? readFileSync(logFile, 'utf8')
          .split('\n')
          .filter(Boolean)
          .map((l) => JSON.parse(l) as Dispatch)
      : [];
    return { code, json, stderr: errBuf, dispatches };
  } finally {
    process.chdir(prevCwd);
    for (const [k, v] of saved) {
      if (v === undefined) delete process.env[k];
      else process.env[k] = v;
    }
  }
}

const TIMEOUT = 30000;

// ---------------------------------------------------------------------------
// DoD 1 + 3: --executor=codex-cli resolves the codex template and runs a
// step end-to-end, producing a valid step record matching the engine's shape
// ---------------------------------------------------------------------------

describe('--executor=codex-cli drives a step through DEFAULT_CODEX_EXECUTOR_TEMPLATE', () => {
  test('the run completes, and the persisted record matches the engine-expected shape', async () => {
    const { root, stepPath } = scaffold();
    const plan = computePlan(root);
    const fakeCodex = join(root, 'fake-codex.ts');
    writeFileSync(fakeCodex, FAKE_CODEX_SRC, 'utf8');
    const logFile = join(root, 'dispatches.jsonl');
    process.env.PIPELINE_DRIVE_EXECUTOR_CMD = armedTemplate(root, fakeCodex);
    try {
      const r = await drive(
        root,
        'codex-e2e',
        ['--start', plan.steps[0].path, '--executor', 'codex-cli', '--default-model', 'gpt-test-model', '--default-effort', 'low'],
        logFile,
      );

      expect(r.code).toBe(0);
      expect(r.json?.status).toBe('completed');
      // Exactly one dispatch — one step, one codex turn.
      expect(r.dispatches.length).toBe(1);

      // The RECORD the engine actually recorded matches the fixture the fake
      // codex wrote via the record-file channel (rung 2/3 of the ladder).
      // step_id is the filename stem (no step_id: frontmatter here) — '01-only'.
      const recordFile = join(root, '.runtime', 'codex-e2e', 'records', '01-only.json');
      expect(existsSync(recordFile)).toBe(true);
      const record = JSON.parse(readFileSync(recordFile, 'utf8'));
      expect(record).toEqual({
        outcome: 'completed',
        summary: 'codex template probe',
        next_iteration: 'PIPELINE_COMPLETE',
        has_improvement_brief: false,
        kind: 'step',
      });

      // The recovery ladder's rung: the record FILE channel won, not a
      // structured_output / final-text guess — exactly what codex-cli's
      // verified channel set predicts (see DEFAULT_CODEX_EXECUTOR_TEMPLATE).
      expect(r.stderr).toMatch(/\[drive\] step\.record .*source=record-file\b/);
    } finally {
      delete process.env.PIPELINE_DRIVE_EXECUTOR_CMD;
    }
  }, TIMEOUT);

  test('the spawned argv carries every MAPPED placeholder and NONE of the unmapped ones', async () => {
    const { root } = scaffold();
    const plan = computePlan(root);
    const fakeCodex = join(root, 'fake-codex.ts');
    writeFileSync(fakeCodex, FAKE_CODEX_SRC, 'utf8');
    const logFile = join(root, 'dispatches.jsonl');
    process.env.PIPELINE_DRIVE_EXECUTOR_CMD = armedTemplate(root, fakeCodex);
    try {
      const r = await drive(
        root,
        'codex-argv',
        ['--start', plan.steps[0].path, '--executor', 'codex-cli', '--default-model', 'gpt-test-model', '--default-effort', 'medium'],
        logFile,
      );
      expect(r.code).toBe(0);
      const [dispatch] = r.dispatches;
      expect(dispatch).toBeDefined();
      const { argv, prompt } = dispatch;

      // Static flags this template always carries.
      expect(argv).toContain('exec');
      expect(argv).toContain('--json');
      expect(argv).toContain('--skip-git-repo-check');

      // {model} — VERIFIED direct flag.
      expect(flagValue(argv, '--model')).toBe('gpt-test-model');

      // {effort} — VERIFIED via `-c model_reasoning_effort=…`.
      expect(argv).toContain('-c');
      expect(argv).toContain('model_reasoning_effort=medium');

      // {permissions} — translated via codexSandboxFor: the default
      // permission mode (no frontmatter override) is 'bypassPermissions',
      // which maps to codex's own no-gate value.
      expect(flagValue(argv, '--sandbox')).toBe('danger-full-access');

      // {record_dir} — the --add-dir grant, pointing at the DROP dir the
      // step_record_file line (below) lives inside.
      const addDir = flagValue(argv, '--add-dir');
      expect(addDir).not.toBeNull();
      const m = /^step_record_file = (.+)$/m.exec(prompt);
      expect(m).not.toBeNull();
      expect(m![1].startsWith(addDir!)).toBe(true);

      // {schema} / --output-schema — NOT used (documented gap: strict-schema
      // incompatibility, reproduced live).
      expect(argv).not.toContain('--output-schema');

      // --agent / {plugin_dir} — NO equivalent; neither flag exists here.
      expect(argv).not.toContain('--agent');
      expect(argv).not.toContain('--plugin-dir');

      // {session} — no pre-mint equivalent; codex-cli's session suppression
      // (appendSessionIfAbsent:false) means NEITHER claude-style flag leaks
      // into a template that carries no {session} token.
      expect(argv).not.toContain('--session-id');
      expect(argv).not.toContain('--resume');
    } finally {
      delete process.env.PIPELINE_DRIVE_EXECUTOR_CMD;
    }
  }, TIMEOUT);
});

// ---------------------------------------------------------------------------
// DoD 2 (surfaced at runtime): the three "no equivalent" gaps are reported
// once, at construction — never once per step.
// ---------------------------------------------------------------------------

describe('codex-cli gaps are surfaced at runtime, exactly once per run', () => {
  test('--agent/{plugin_dir}, --output-schema and session-resume gaps are each reported exactly once', async () => {
    const { root } = scaffold();
    // A SECOND step, so "once per run" is not vacuous against a one-step run.
    mkdirSync(join(root, 'steps'), { recursive: true });
    writeFileSync(join(root, 'steps', '02-second.md'), '# second step\n');
    const plan = computePlan(root);
    const fakeCodex = join(root, 'fake-codex.ts');
    // This fake chains step 1 → step 2 → PIPELINE_COMPLETE by reading which
    // step the prompt names, so the run genuinely dispatches twice — "once
    // per run" below is not vacuous against a one-dispatch run.
    writeFileSync(
      fakeCodex,
      `// generated by tests/drive-executor-codex-template.test.ts (two-step variant)
import { appendFileSync, writeFileSync, mkdirSync } from 'node:fs';
import { dirname } from 'node:path';

const argv = process.argv.slice(2);
const prompt = await Bun.stdin.text();
appendFileSync(process.env.PIPELINE_CODEX_LOG, JSON.stringify({ argv, prompt }) + '\\n', 'utf8');

const m = /^step_record_file = (.+)$/m.exec(prompt);
const recordFile = m ? m[1].trim() : null;
const isFirst = prompt.includes('01-only.md');
if (recordFile) {
  mkdirSync(dirname(recordFile), { recursive: true });
  writeFileSync(
    recordFile,
    JSON.stringify({
      outcome: 'completed',
      summary: 'step',
      next_iteration: isFirst ? ${JSON.stringify(join(root, 'steps', '02-second.md'))} : 'PIPELINE_COMPLETE',
      has_improvement_brief: false,
    }),
    'utf8',
  );
}
process.stdout.write(JSON.stringify({ type: 'thread.started', thread_id: '0' }) + '\\n');
process.stdout.write(JSON.stringify({ type: 'item.completed', item: { id: 'i', type: 'agent_message', text: 'DONE' } }) + '\\n');
process.stdout.write(JSON.stringify({ type: 'turn.completed', usage: { input_tokens: 1, output_tokens: 1 } }) + '\\n');
process.exit(0);
`,
      'utf8',
    );
    const logFile = join(root, 'dispatches.jsonl');
    process.env.PIPELINE_DRIVE_EXECUTOR_CMD = armedTemplate(root, fakeCodex);
    try {
      const r = await drive(root, 'codex-gaps', ['--start', plan.steps[0].path, '--executor', 'codex-cli'], logFile);
      expect(r.code).toBe(0);
      expect(r.dispatches.length).toBe(2); // both steps really ran

      const count = (needle: string): number => r.stderr.split(needle).length - 1;
      expect(count("has no equivalent to claude's --agent")).toBe(1);
      expect(count('does not use --output-schema for the step record')).toBe(1);
      expect(count('never resumes a codex thread')).toBe(1);
    } finally {
      delete process.env.PIPELINE_DRIVE_EXECUTOR_CMD;
    }
  }, TIMEOUT);
});

// ---------------------------------------------------------------------------
// DoD 4: --executor-cmd still overrides the codex default, exactly as it
// does the claude one.
// ---------------------------------------------------------------------------

describe('--executor-cmd overrides DEFAULT_CODEX_EXECUTOR_TEMPLATE, as it does the others', () => {
  test('a custom --executor-cmd wins over the built-in codex template', async () => {
    const { root } = scaffold();
    const plan = computePlan(root);
    const fakeCodex = join(root, 'fake-codex.ts');
    writeFileSync(fakeCodex, FAKE_CODEX_SRC, 'utf8');
    const logFile = join(root, 'dispatches.jsonl');
    // A custom template carrying a marker flag DEFAULT_CODEX_EXECUTOR_TEMPLATE
    // never has — its presence in the spawned argv is proof the override, not
    // the built-in default, was used.
    const customTemplate = `bun ${fakeCodex} --my-custom-marker`;
    try {
      const r = await drive(
        root,
        'codex-cmd-override',
        ['--start', plan.steps[0].path, '--executor', 'codex-cli', '--executor-cmd', customTemplate],
        logFile,
      );
      expect(r.code).toBe(0);
      const [dispatch] = r.dispatches;
      expect(dispatch.argv).toContain('--my-custom-marker');
      expect(dispatch.argv).not.toContain('--skip-git-repo-check'); // the built-in default's own flag, absent here
    } finally {
      delete process.env.PIPELINE_DRIVE_EXECUTOR_CMD;
    }
  }, TIMEOUT);
});

// ---------------------------------------------------------------------------
// {permissions} translation — a non-default step permission mode
// ---------------------------------------------------------------------------

describe('codex-cli {permissions} translation (codexSandboxFor)', () => {
  test("a step's permission-mode: plan maps to --sandbox read-only", async () => {
    const root = mkdtempSync(join(tmpdir(), 'drive-codex-plan-'));
    created.push(root);
    writeFileSync(join(root, 'PIPELINE.md'), '# P\n\n## End State\ndone\n');
    mkdirSync(join(root, 'steps'), { recursive: true });
    const stepPath = join(root, 'steps', '01-plan.md');
    writeFileSync(stepPath, '---\npermission-mode: plan\n---\n# plan-mode step\n');
    const plan = computePlan(root);
    const fakeCodex = join(root, 'fake-codex.ts');
    writeFileSync(fakeCodex, FAKE_CODEX_SRC, 'utf8');
    const logFile = join(root, 'dispatches.jsonl');
    process.env.PIPELINE_DRIVE_EXECUTOR_CMD = armedTemplate(root, fakeCodex);
    try {
      const r = await drive(root, 'codex-plan-mode', ['--start', plan.steps[0].path, '--executor', 'codex-cli'], logFile);
      expect(r.code).toBe(0);
      const [dispatch] = r.dispatches;
      expect(flagValue(dispatch.argv, '--sandbox')).toBe('read-only');
    } finally {
      delete process.env.PIPELINE_DRIVE_EXECUTOR_CMD;
    }
  }, TIMEOUT);

  test('an UNRECOGNISED permission-mode value falls back to workspace-write and warns once', async () => {
    const root = mkdtempSync(join(tmpdir(), 'drive-codex-unknown-perm-'));
    created.push(root);
    writeFileSync(join(root, 'PIPELINE.md'), '# P\n\n## End State\ndone\n');
    mkdirSync(join(root, 'steps'), { recursive: true });
    const stepPath = join(root, 'steps', '01-weird.md');
    writeFileSync(stepPath, '---\npermission-mode: some-future-mode\n---\n# weird step\n');
    const plan = computePlan(root);
    const fakeCodex = join(root, 'fake-codex.ts');
    writeFileSync(fakeCodex, FAKE_CODEX_SRC, 'utf8');
    const logFile = join(root, 'dispatches.jsonl');
    process.env.PIPELINE_DRIVE_EXECUTOR_CMD = armedTemplate(root, fakeCodex);
    try {
      const r = await drive(root, 'codex-unknown-perm', ['--start', plan.steps[0].path, '--executor', 'codex-cli'], logFile);
      expect(r.code).toBe(0);
      const [dispatch] = r.dispatches;
      expect(flagValue(dispatch.argv, '--sandbox')).toBe('workspace-write');
      expect(r.stderr).toContain("no --sandbox mapping for permission-mode 'some-future-mode'");
    } finally {
      delete process.env.PIPELINE_DRIVE_EXECUTOR_CMD;
    }
  }, TIMEOUT);
});
